export enum PerfilEnum {
  COMPRADOR = 'Comprador',
  DIRETORIA = 'Diretoria',
  RECEBIMENTO = 'Recebimento',
  ADMIN = 'Admin'
}

export enum StatusPedido {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
  ENVIADO = 'ENVIADO',
  CONFIRMADO = 'CONFIRMADO',
  RECEBIDO_PARCIAL = 'RECEBIDO_PARCIAL',
  RECEBIDO_COMPLETO = 'RECEBIDO_COMPLETO',
  CANCELADO = 'CANCELADO'
}
