export enum PerfilEnum {
  COMPRADOR = 'Comprador',
  DIRETORIA = 'Diretoria',
  RECEBIMENTO = 'Recebimento',
  ADMIN = 'Admin'
}

export enum StatusPedido {
  RASCUNHO = 'RASCUNHO',
  ANALISE_COTACAO = 'ANALISE_COTACAO',
  ENVIADO_FORNECEDOR = 'ENVIADO_FORNECEDOR',
  AGUARDANDO_FATURAMENTO = 'AGUARDANDO_FATURAMENTO',
  EM_ROTA = 'EM_ROTA',
  RECEBIMENTO_NOTA = 'RECEBIMENTO_NOTA',
  APROVADO_DIRETORIA = 'APROVADO_DIRETORIA',
  CANCELADO = 'CANCELADO'
}
